// AUTO-GENERATED by scripts/sync-onramp-allowlist.js. Do not edit directly.
export const ALLOWED_PROVIDER_HOSTS = {
  "banxa": [
    "banxa.com",
    "checkout.banxa.com",
    "docs.banxa.com"
  ],
  "binance-bahrain": [
    "binance.bh",
    "cbb.gov.bh"
  ],
  "binance-th": [
    "binance.th",
    "sec.or.th"
  ],
  "binance-tr": [
    "binance.com",
    "masak.hmb.gov.tr"
  ],
  "bit2me": [
    "bit2me.com",
    "portalclientebde.bde.es"
  ],
  "bitbank": [
    "fsa.go.jp",
    "support.bitbank.cc"
  ],
  "bitflyer": [
    "bitflyer.com",
    "fsa.go.jp"
  ],
  "bithumb": [
    "bithumb.com",
    "fsc.go.kr"
  ],
  "bitkub": [
    "bitkub.com",
    "sec.or.th"
  ],
  "bitopro": [
    "bitopro.com",
    "law.fsc.gov.tw"
  ],
  "bitpanda": [
    "bitpanda.com"
  ],
  "bits-of-gold": [
    "bitsofgold.co.il",
    "gov.il"
  ],
  "bitso": [
    "bitso.com",
    "cnv.gov.ar",
    "gob.mx"
  ],
  "bitso-co": [
    "bitso.com"
  ],
  "bitstamp": [
    "bitstamp.net",
    "cssf.lu",
    "search.csb.gov.lv"
  ],
  "bitvavo": [
    "bitvavo.com",
    "dnb.nl"
  ],
  "btcturk": [
    "btcturk.com",
    "masak.hmb.gov.tr"
  ],
  "btcx": [
    "bt.cx",
    "fi.se"
  ],
  "buda": [
    "buda.com"
  ],
  "buda-co": [
    "buda.com"
  ],
  "buda-pe": [
    "buda.com"
  ],
  "coinbase": [
    "centralbank.ie",
    "coinbase.com",
    "cssf.lu",
    "eservices.mas.gov.sg",
    "help.coinbase.com",
    "portal.mvp.bafin.de",
    "securities-administrators.ca"
  ],
  "coincheck": [
    "coincheck.com",
    "fsa.go.jp"
  ],
  "coindcx": [
    "coindcx.com",
    "fiuindia.gov.in"
  ],
  "coinmate": [
    "coinmate.io"
  ],
  "coinmena": [
    "cbb.gov.bh",
    "coinmena.com",
    "fsa.gov.om"
  ],
  "coinmetro": [
    "coinmetro.com",
    "fiu.ee"
  ],
  "coinmotion": [
    "coinmotion.com",
    "finanssivalvonta.fi"
  ],
  "coinone": [
    "coinone.co.kr",
    "fsc.go.kr"
  ],
  "coins-ph": [
    "bsp.gov.ph",
    "coins.ph"
  ],
  "coinspot": [
    "austrac.gov.au",
    "coinspot.com.au"
  ],
  "crypto-com": [
    "amf-france.org",
    "crypto.com"
  ],
  "easy-crypto-nz": [
    "easycrypto.com",
    "fspr.govt.nz"
  ],
  "firi": [
    "finanstilsynet.no",
    "firi.com"
  ],
  "gemini": [
    "dfs.ny.gov",
    "gemini.com",
    "register.fca.org.uk"
  ],
  "hashkey": [
    "hashkey.com",
    "sfc.hk"
  ],
  "independent-reserve": [
    "austrac.gov.au",
    "eservices.mas.gov.sg",
    "independentreserve.com"
  ],
  "indodax": [
    "bappebti.go.id",
    "indodax.com"
  ],
  "ismynt": [
    "cb.is",
    "ismynt.is"
  ],
  "kraken": [
    "gob.mx",
    "kraken.com",
    "osc.ca"
  ],
  "luno": [
    "fsca.co.za",
    "luno.com"
  ],
  "luno-ke": [
    "luno.com"
  ],
  "luno-my": [
    "luno.com",
    "sc.com.my"
  ],
  "luno-ng": [
    "luno.com"
  ],
  "m2": [
    "adgm.com",
    "m2.com"
  ],
  "maicoin-max": [
    "group.maicoin.com",
    "law.fsc.gov.tw",
    "maicoin.com"
  ],
  "mercado-bitcoin": [
    "bcb.gov.br",
    "mercadobitcoin.com.br"
  ],
  "moonpay": [
    "buy.moonpay.com",
    "dev.moonpay.com",
    "moonpay.com",
    "support.moonpay.com"
  ],
  "myntkaup": [
    "cb.is",
    "myntkaup.is"
  ],
  "nbx": [
    "finanstilsynet.no",
    "nbx.com"
  ],
  "newton": [
    "newton.co",
    "osc.ca"
  ],
  "osl": [
    "osl.com",
    "sfc.hk"
  ],
  "paribu": [
    "masak.hmb.gov.tr",
    "paribu.com"
  ],
  "pdax": [
    "bsp.gov.ph",
    "pdax.ph"
  ],
  "pintu": [
    "bappebti.go.id",
    "pintu.co.id"
  ],
  "rain": [
    "adgm.com",
    "cbb.gov.bh",
    "fsa.gov.om",
    "rain.com"
  ],
  "ramp": [
    "app.ramp.network",
    "rampnetwork.com"
  ],
  "safello": [
    "fi.se",
    "safello.com"
  ],
  "spectrocoin": [
    "spectrocoin.com"
  ],
  "swissquote": [
    "en.swissquote.com",
    "finma.ch"
  ],
  "tokenize": [
    "kdx.com.my",
    "sc.com.my"
  ],
  "tradesilvania": [
    "tradesilvania.com"
  ],
  "transak": [
    "global.transak.com",
    "transak.com"
  ],
  "upbit-kr": [
    "fsc.go.kr",
    "upbit.com"
  ],
  "upbit-th": [
    "sec.or.th",
    "th.upbit.com"
  ],
  "valr": [
    "valr.com"
  ],
  "wazirx": [
    "fiuindia.gov.in",
    "wazirx.com"
  ],
  "whitebit": [
    "whitebit.com"
  ],
  "xrex": [
    "prnewswire.com",
    "xrex.io"
  ],
  "yellow-card": [
    "yellowcard.io"
  ],
  "zonda": [
    "zondaglobal.com"
  ]
} as const;
export type AllowedProviderId = keyof typeof ALLOWED_PROVIDER_HOSTS;
export type AllowedProviderHosts = typeof ALLOWED_PROVIDER_HOSTS;
